account_id = "08e9dfbf86a3d264a8b800d53d4fa71f"
name = "cloudflare-social-network"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2021-11-10"

kv_namespaces = [
   { binding = "POSTS_KV", preview_id = "266d41a6e10341d9930a7b8a82a07fdb" }
]